/* 3.1 */
SELECT * FROM EMPLOYEE WHERE FIRST_NAME = 'PRAKHAR'

/* 3.1.1 */
SELECT * FROM EMPLOYEE WHERE ID > 2 AND LAST_NAME = 'KUMAR'

/* 3.1.2 */
SELECT * FROM EMPLOYEE WHERE FIRST_NAME = 'PRAKHAR' OR LAST_NAME = 'KUMAR'

/* 3.1.3 */
SELECT * FROM EMPLOYEE WHERE NOT FIRST_NAME = 'JOHN'