/* 1.A */
INSERT INTO EMPLOYEE VALUES (1, 'PRAKHAR', 'PARWAL', '00-0000000')

/* 1.B */
INSERT INTO EMPLOYEE VALUES (1, 'TEST', 'EMPLOYEE', '00-99999999')

/* 1.C */
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'TEST', 'EMPLOYEE')

/* 2.A */
SELECT * FROM EMPLOYEE 

/* 2.B */
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEE 

/* 3.A */
UPDATE EMPLOYEE SET PHONE_NUMBER = '00-55555555'
UPDATE EMPLOYEE SET PHONE_NUMBER = '00-00000000' WHERE ID = 1 

/* 4.A */
DELETE FROM EMPLOYEE WHERE ID = 2 

/* 4.B */
UPDATE EMPLOYEE SET PHONE_NUMBER = NULL

/* 4.C */
TRUNCATE TABLE EMPLOYEE 
