/*1*/
CREATE TABLE EMPLOYEE 
(
	ID INT NOT NULL,
	FIRST_NAME NVARCHAR(100),
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID)
);


/* 2.a */
ALTER TABLE EMPLOYEE ADD LAST_NAME NVARCHAR(100)

/* 2.b */
ALTER TABLE EMPLOYEE ADD PHONE_NUMBER INT
ALTER TABLE EMPLOYEE ALTER COLUMN PHONE_NUMBER NVARCHAR(100)
